#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "$SCRIPT_DIR" || ( echo "missing directory $SCRIPT_DIR" && exit 1 )

maketest() {
    echo maketest "$@"
    for src_test_name_ext in "$@"
    do
	if [ ! -r "$src_test_name_ext" ]
	then
	    echo "skiping $src_test_name_ext"
	    continue
	fi
	test_name_ext=$(basename $src_test_name_ext)
	test_name="${test_name_ext%.*}"
	test_bin="bin/$(uname -s)-$(uname -m)/$test_name"
	if ! make "$test_bin"
	then
	    fail="$fail make $test_name"
	else
	    if [ -x "./$test_bin" ] && "./$test_bin"
	    then
		pass="$pass $test_name"
	    else
		fail="$fail $test_name"
	    fi
	fi
    done
}

if [ $# -gt 0 ]
then
    maketest "$@"
else
    maketest src/test_*.cpp src/test_*.c
fi

if [ "$pass" != "" ]
then
  echo "passed build&test:$pass"
fi
if [ "$fail" != "" ]
then
   echo "failed make|test:$fail"
   exit 1
fi

echo "all built/test passed!"
exit 0

