#pragma once
#define CALC_TOKEN_YYEOF 0
#define CALC_TOKEN_YYUNDEF 257
#define CALC_TOKEN_ADD 258
#define CALC_TOKEN_SUB 259
#define CALC_TOKEN_MUL 260
#define CALC_TOKEN_DIV 261
#define CALC_TOKEN_LP 262
#define CALC_TOKEN_RP 263
#define CALC_TOKEN_NUM 264
#define CALC_TOKEN_ID 265
#define CALC_TOKEN_EOL 266
